// Generated by tools/bin/plugin generate from plugin.json; do not edit.
#import <NgonLayer/NgonLayer.h>

#include "ngon_layer.h"

NSErrorDomain const MLNNgonLayerPluginErrorDomain = @"org.maplibre.plugins.ngon-layer";

@implementation MLNNgonLayerPlugin

+ (NSString *)version {
    return @"0.1.1";
}

+ (BOOL)registerPluginWithError:(NSError **)error {
    char message[512] = {};
    const mln_plugin_status status = mln_ngon_layer_register(&mln_plugin_register_v1, message, sizeof(message));
    if (status == MLN_PLUGIN_STATUS_OK || status == MLN_PLUGIN_STATUS_ALREADY_REGISTERED) {
        return YES;
    }
    if (error) {
        NSString *description = message[0] ? [NSString stringWithUTF8String:message]
                                            : @"MapLibre rejected the Ngon layer plugin";
        *error = [NSError errorWithDomain:MLNNgonLayerPluginErrorDomain
                                     code:status
                                 userInfo:@{NSLocalizedDescriptionKey: description ?: @""}];
    }
    return NO;
}

@end
